# Generated by Django 3.2.4 on 2021-07-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Data',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(default='', max_length=500, null=True)),
                ('Website', models.CharField(default='', max_length=500, null=True)),
                ('Employee_Range', models.IntegerField(default=0, null=True)),
                ('Industry', models.CharField(default='', max_length=500, null=True)),
                ('Address_1', models.CharField(default='', max_length=500, null=True)),
                ('Address_2', models.CharField(default='', max_length=500, null=True)),
                ('City', models.CharField(default='', max_length=500, null=True)),
                ('Zip_Code', models.CharField(default='', max_length=500, null=True)),
                ('Country', models.CharField(default='', max_length=500, null=True)),
                ('First_Name', models.CharField(default='', max_length=500, null=True)),
                ('Last_Name', models.CharField(default='', max_length=500, null=True)),
                ('Job_Title', models.CharField(default='', max_length=500, null=True)),
                ('LinkedIn_URL', models.CharField(default='', max_length=500, null=True)),
                ('Public_Profile', models.CharField(default='', max_length=500, null=True)),
                ('Email_Id', models.EmailField(default='', max_length=254, null=True)),
                ('Contact_Num', models.IntegerField(default=0, null=True)),
                ('Job_Url', models.CharField(default='', max_length=500, null=True)),
                ('Job_Opening', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'Data',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('Photo', models.ImageField(null=True, upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dob', models.DateField(max_length=20, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('District', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
