# Generated by Django 2.2.14 on 2021-07-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='District',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='State',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password1',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password2',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
