# Generated by Django 2.2.14 on 2021-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0003_auto_20210731_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
