# Generated by Django 2.2.14 on 2021-08-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0005_auto_20210801_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_data',
            name='Account_Name',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Additional_information',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Address_3',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Business_Solution',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Company_Founded_Year',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Company_Linkedin_URL',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Company_Techology',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Company_Type',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Country_Code',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Department',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Direct_Number',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Employee_size',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Prospect_City',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Prospect_Country',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Prospect_State',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Revenue',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='Revenue_link',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company_data',
            name='State',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company_data',
            name='Employee_Range',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
