# Generated by Django 2.2.14 on 2021-08-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0006_auto_20210803_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='District',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='State',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='Password1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='Password2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uploaded_at',
        ),
    ]
