# Generated by Django 2.2.14 on 2021-08-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0007_auto_20210804_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
