# Generated by Django 2.2.14 on 2021-08-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0008_auto_20210804_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Email',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Last_Name',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Password1',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='First_Name',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Password2',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Photo',
            field=models.ImageField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
