# Generated by Django 2.2.14 on 2021-08-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0010_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='Email_Id',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
