# Generated by Django 2.2.14 on 2021-08-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0012_remove_emp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='Username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
