# Generated by Django 2.2.14 on 2021-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0013_auto_20210804_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='District',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='State',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='Pass1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='Pass2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Email_Id',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='Data1',
        ),
    ]
