# Generated by Django 2.2.14 on 2021-08-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Uploading', '0016_auto_20210805_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
